language = "C"
sys_includes = ["stdint.h"]
no_includes = true
documentation = true
include_guard = "BSANRT_H"
namespace = "bsan_rt"
cpp_compat = true

[parse]
parse_deps = true
include = ["src/lib.rs"] 